SET time_zone = "+09:00";

DROP TABLE IF EXISTS verifys;
DROP TABLE IF EXISTS boards;
DROP TABLE IF EXISTS threads;
DROP TABLE IF EXISTS comments;

CREATE TABLE IF NOT EXISTS verifys (
    id INT PRIMARY KEY AUTO_INCREMENT,
    useruuid VARCHAR(255) NOT NULL,
    userkey VARCHAR(255) NOT NULL,
    userexpiry TIMESTAMP NOT NULL,
    isadmin TINYINT(1) NOT NULL DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS boards (
    id INT PRIMARY KEY AUTO_INCREMENT,
    boarduuid VARCHAR(255) NOT NULL,
    boardname VARCHAR(255) NOT NULL,
    boarddescription VARCHAR(255) NOT NULL,
    boardpassword VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS threads (
    id INT PRIMARY KEY AUTO_INCREMENT,
    boarduuid VARCHAR(255) NOT NULL,
    threaduuid VARCHAR(255) NOT NULL,
    threadname VARCHAR(255) NOT NULL,
    readonly TINYINT(1) NOT NULL DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS comments (
    id INT PRIMARY KEY AUTO_INCREMENT,
    threaduuid VARCHAR(255) NOT NULL,
    commentuuid VARCHAR(255) NOT NULL,
    useruuid VARCHAR(255) NOT NULL,
    nickname VARCHAR(255) NOT NULL,
    context VARCHAR(255) NOT NULL,
    isadmin TINYINT(1) NOT NULL DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);